# A

In [1]:
import torch

In [2]:
M = 5
N = 3

beta = .2
alpha = .5
D = 1;

In [3]:
X = torch.rand((M,N))
I = torch.eye(M)

In [4]:
X = torch.rand((M,N))
X.requires_grad_(True)

tensor([[0.5459, 0.3506, 0.3302],
        [0.2731, 0.6354, 0.0331],
        [0.8603, 0.8923, 0.3528],
        [0.4179, 0.8398, 0.9095],
        [0.6237, 0.8274, 0.3386]], requires_grad=True)

In [5]:
K = 1/beta*I + alpha*torch.matmul(X,X.T)
L1 = -D/2 * torch.log(torch.det(K))
L1.backward()
grad_auto = X.grad

In [6]:
grad_manual = -D*alpha/2 * torch.matmul((torch.inverse(K).T + torch.inverse(K)),X)

In [7]:
(grad_auto-grad_manual).max()

tensor(0., grad_fn=<MaxBackward1>)

# B

In [1]:
import torch

In [2]:
M = 5
N = 3
l = 4

beta = .2
alpha = .5
D = 1;

In [3]:
X = torch.rand((M,N))
Y = torch.rand((M,l))
I = torch.eye(M)

In [4]:
X.requires_grad_(True)

tensor([[0.5519, 0.2019, 0.7249],
        [0.9295, 0.1260, 0.2161],
        [0.4982, 0.3786, 0.8228],
        [0.0566, 0.2287, 0.8418],
        [0.9706, 0.8540, 0.0616]], requires_grad=True)

In [5]:
K = 1/beta*I + alpha*torch.matmul(X,X.T)
L2 = -1/2*torch.trace(torch.matmul(torch.matmul(torch.inverse(K),Y),Y.T))

In [6]:
L2.backward()

In [7]:
grad_auto = X.grad

In [8]:
grad_manual = alpha * torch.matmul(torch.matmul(torch.matmul(torch.matmul(torch.inverse(K).T,Y),Y.T),torch.inverse(K).T),X)

In [9]:
(grad_auto-grad_manual).max()

tensor(1.8626e-09, grad_fn=<MaxBackward1>)

In [10]:
grad_auto

tensor([[0.0146, 0.0060, 0.0153],
        [0.0493, 0.0226, 0.0410],
        [0.0314, 0.0152, 0.0259],
        [0.0276, 0.0127, 0.0249],
        [0.0188, 0.0111, 0.0109]])

In [11]:
grad_manual

tensor([[0.0146, 0.0060, 0.0153],
        [0.0493, 0.0226, 0.0410],
        [0.0314, 0.0152, 0.0259],
        [0.0276, 0.0127, 0.0249],
        [0.0188, 0.0111, 0.0109]], grad_fn=<MulBackward0>)