In [8]:
import numpy as np

In [9]:
d = 5
N = 1000
lambd = 0.05
eta = 100000
w_t = np.random.rand(d,1)

In [10]:
1/eta

1e-05

In [11]:
w_true = np.array([[0.5, -.5, 2, 3, 1]]).T
X = np.random.randint(0,10,size=(N,d))
y = np.dot(X,w_true)

In [5]:
def soft_threshold(x):
    if x > lambd/eta:
        return x - lambd/eta
    elif abs(x) <= lambd/eta:
        return 0
    elif x < -lambd/eta:
        return x + lambd/eta
        

In [6]:
for i in range(1000):
    g = np.matmul(X.T,np.dot(X,w_t)-y)
    w_t = np.array([soft_threshold(wi) for wi in (w_t - 1/eta*g)])
    print(w_t)

[[0.70475071]
 [1.39364291]
 [1.4523219 ]
 [1.76325923]
 [1.14986726]]
[[0.62009464]
 [1.17578955]
 [1.42518239]
 [1.79289125]
 [1.06598591]]
[[0.61730371]
 [1.04893714]
 [1.47976743]
 [1.89846681]
 [1.06800195]]
[[0.60637009]
 [0.92397919]
 [1.52099424]
 [1.98668889]
 [1.06101967]]
[[0.59732046]
 [0.80996145]
 [1.55988887]
 [2.06875954]
 [1.05564866]]
[[0.58894415]
 [0.70497381]
 [1.59552201]
 [2.1440758 ]
 [1.05064338]]
[[0.58130095]
 [0.60840923]
 [1.62828324]
 [2.21330855]
 [1.04609561]]
[[0.57431441]
 [0.51958003]
 [1.65839079]
 [2.27693661]
 [1.04195102]]
[[0.56792941]
 [0.43786807]
 [1.686061  ]
 [2.33541543]
 [1.03817558]]
[[0.56209394]
 [0.36270312]
 [1.7114909 ]
 [2.38916185]
 [1.03473648]]
[[0.55676066]
 [0.29356077]
 [1.73486183]
 [2.43855911]
 [1.03160402]]
[[0.55188628]
 [0.22995858]
 [1.7563404 ]
 [2.48395935]
 [1.02875106]]
[[0.54743126]
 [0.17145275]
 [1.77607977]
 [2.52568622]
 [1.02615287]]
[[0.54335947]
 [0.11763504]
 [1.79422071]
 [2.56403711]
 [1.02378688]]
[[0.53

 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.99999749]]
[[ 0.49999747]
 [-0.49999051]
 [ 1.9999976 ]
 [ 2.99999713]
 [ 0.9999974

In [12]:
for i in range(10000):
    g = np.matmul(X.T,np.dot(X,w_t)-y)
    z = w_t - 1/eta * g
    w_t = np.sign(z) * np.maximum(np.abs(z) - lambd/eta,0)
    print(w_t)

[[1.05191621]
 [1.29340737]
 [1.23558037]
 [1.43162511]
 [1.18028122]]
[[0.97686464]
 [1.09745246]
 [1.2549484 ]
 [1.52988178]
 [1.12788778]]
[[0.94755344]
 [0.95919319]
 [1.31412753]
 [1.65977539]
 [1.12064536]]
[[0.91727331]
 [0.83036433]
 [1.36602452]
 [1.7756147 ]
 [1.11115181]]
[[0.88910766]
 [0.71309525]
 [1.4142096 ]
 [1.88157287]
 [1.10259311]]
[[0.86272793]
 [0.60616144]
 [1.45875126]
 [1.97831004]
 [1.09468884]]
[[0.83804497]
 [0.50866391]
 [1.49993529]
 [2.06664454]
 [1.08740143]]
[[0.81495837]
 [0.41976824]
 [1.53801121]
 [2.14730825]
 [1.08068121]]
[[0.79337359]
 [0.33871482]
 [1.57321124]
 [2.22096999]
 [1.07448351]]
[[0.77320066]
 [0.26481112]
 [1.60575041]
 [2.28824001]
 [1.06876719]]
[[0.75435421]
 [0.19742584]
 [1.63582788]
 [2.34967516]
 [1.06349437]]
[[0.73675322]
 [0.13598346]
 [1.66362808]
 [2.40578363]
 [1.05863021]]
[[0.720321  ]
 [0.07995934]
 [1.68932181]
 [2.45702916]
 [1.05414264]]
[[0.70498496]
 [0.02887519]
 [1.7130672 ]
 [2.50383497]
 [1.05000215]]
[[ 0.6

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.4999974

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.4999974

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.4999974

[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.4999974

 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.9999970

[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.49999742]
 [-0.49999089]
 [ 1.99999713]
 [ 2.99999791]
 [ 0.99999703]]
[[ 0.4999974